## Практическое задание 3

In [1]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

### __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$:  
   __Ответ:__ Произведение матриц $AB$ и $BA$ невозможно, так как число столбцов матрицы $A$ не равно числу строк матрицы $B$ и наоборот.
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$:  
   __Ответ:__ Произведение матриц $AB$ определено. Размерность полученной матрицы составляет $2\times3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$:  
   __Ответ:__ Произвдение матриц $AB$ и $BA$ определено. Размерность полученных матриц составляет $8\times8$ и $3\times3$, соответсвенно
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$:  
   __Ответ:__ Произвдение матриц $AB$ и $BA$ определено. Размерность полученных матриц составляет $4\times4$

### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A+B = \begin{pmatrix} 1+4 & -2-1\\ 3+0 & 0+5\\ \end{pmatrix}=\begin{pmatrix} 5 & -3\\ 3 & 5\\ \end{pmatrix}$$

$$A\times B=\begin{pmatrix} 1\cdot4+(-2)\cdot0 & 1\cdot(-1) + (-2)\cdot5\\ 3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5\\ \end{pmatrix}=\begin{pmatrix} 4 & -11\\ 12 & -3\\ \end{pmatrix}$$

$$B\times A=\begin{pmatrix} 4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\ 0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0\\ \end{pmatrix}= \begin{pmatrix} 1 & -8\\ 15 & 0\\ \end{pmatrix}$$

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(a + b, np.dot(a, b), np.dot(b, a), sep='\n\n')

[[ 5 -3]
 [ 3  5]]

[[  4 -11]
 [ 12  -3]]

[[ 1 -8]
 [15  0]]


### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A-2B+4C=3\begin{pmatrix} 1&7\\3&-6\\\end{pmatrix}-2\begin{pmatrix} 0&5\\2&-1\\\end{pmatrix}+4\begin{pmatrix} 2&-4\\1&1\\\end{pmatrix}=\begin{pmatrix} 3&21\\9&-18\\\end{pmatrix}+\begin{pmatrix} 0&-10\\-4&2\\\end{pmatrix}+\begin{pmatrix} 8&-16\\4&4\\\end{pmatrix}=\begin{pmatrix} 11&-5\\9&-12\\\end{pmatrix}$$

In [3]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(3*a-2*b+4*c)

[[ 11  -5]
 [  9 -12]]


### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^T=\begin{pmatrix}4&5&2\\1&-2&3\\\end{pmatrix}$$

$$AA^T=\begin{pmatrix} 
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 4\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3\\
\end{pmatrix} =
\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 2\\
11 & 4 & 10\\
\end{pmatrix}$$

$$A^TA=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3\\
\end{pmatrix} =
\begin{pmatrix}
45 & 0\\
0 & 14\\
\end{pmatrix}$$

In [4]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(a.dot(a.T), a.T.dot(a), sep='\n\n')

[[17 18 11]
 [18 29  4]
 [11  4 13]]

[[45  0]
 [ 0 14]]


### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
a = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
b = [[1, 2, 3], [4, 5, 6]]

In [6]:
class MyError(Exception):
    def __init__(self, text):
        self.txt = text


def rows_len_check(matrix): 
    """
    функция для сравнения количества элементов в строках. Она нам ещё пригодится :)
    """
    if len(matrix) != len([el for el in matrix if len(el) == len(matrix[0])]):
        raise MyError('Количество элементов в строках матрицы должны совпадать')


def rows1_columns2_check(matrix1, matrix2):
    """
    функция для сравнения количества столбцов в первой матрице с количеством строк во второй. Она нам ещё пригодится :)
    """
    if len(matrix2) != len(matrix1[0]):
        raise MyError('Количество столбцов первой матрицы должно совподать с количеством строк во второй матрице')


def matrix_dot(matrix1: [list], matrix2: [list]) -> [list]:
    rows_len_check(matrix1)
    rows_len_check(matrix2)
    rows1_columns2_check(matrix1, matrix2)
    answer = []
    for i in range(len(a)):
        answer.append([])
        for j in range(len(b[0])):
            answer[i].append(0)
            for w in range(len(b)):
                answer[i][j] += matrix1[i][w] * matrix2[w][j]
    return answer

In [7]:
print(*matrix_dot(a, b), sep='\n')
print(np.dot(a, b))

[9, 12, 15]
[19, 26, 33]
[29, 40, 51]
[39, 54, 69]
[49, 68, 87]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]
 [39 54 69]
 [49 68 87]]


## Практическое задание 4

### __1.__ Вычислить определитель:

a)
$$\begin{vmatrix}
\sin{x} & -\cos{x}\\ 
\cos{x} & \sin{x}
\end{vmatrix} = \sin^2{x}+\cos^2{x}=1$$

б)    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot5\cdot9=180$$

In [8]:
task1b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(task1b)

180.0

в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = 0$$
третья строка линейно-зависима от второй строки.

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1\begin{vmatrix} 5 & 6\\ 8 & 9\\\end{vmatrix} -2 \begin{vmatrix} 4 & 6\\ 7 & 9\\\end{vmatrix} + 3\begin{vmatrix} 4 & 5\\ 7 & 8\\\end{vmatrix}= -3+12-9=0$$

In [9]:
task1v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(task1v):.0f}')

-0


### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det(A)\cdot det(A) = 4 \cdot 4 = 16$ (Исходя из 9 свойства);
    
   б) $det(A^{T}) = det(A) = 4$ (Исходя из 1 свойства);
    
   в) $det(2A) = det(A)\cdot 2^{rank(A)}=4\cdot2^{rank(A)}$ (Исходя из 2 свойства).

### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Вторая строка линейно-зависима от первой, следовательно, определитель равен нулю, следовательно матрица _вырожденная_ или _сингулярная_

### __4.__ Найти ранг матрицы:

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$  

Третья строка является линейной комбинацией первых друх. Отбросим её.  

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$  

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$  

Таким образом ранг матрицы равен $2$.

In [10]:
task4a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(task4a)

2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Третья строка является линейной комбинацией первых двух. Отбросим её.

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Отзеркалим матрицу по столбцам.  

$\begin{pmatrix}
1 & 2 & 0 & 0\\ 
2 & 2 & 0 & 0\\ 
6 & 5 & 3 & 2
\end{pmatrix}$  

Транспонируем матрицу.

$\begin{pmatrix}
1 & 2 & 6\\ 
2 & 2 & 5\\ 
0 & 0 & 3\\
0 & 0 & 2
\end{pmatrix}$  

Вычтем из второй строки первую с множителем $2$.

$\begin{pmatrix}
1 & 2 & 6\\ 
0 & -2 & -7\\ 
0 & 0 & 3\\
0 & 0 & 2
\end{pmatrix}$

Таким образом ранг матрицы равен 3.

In [11]:
task4b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(task4b)

3

In [12]:
test_matrix = np.array([[1, 2, 3, 4], [9, -2, 10, 6], [4, 0, 17, -4], [3, 1, 1, 111]])
np.linalg.det(test_matrix)

-24534.000000000007

### Написать на Python функцию для получения определителя матрицы, не используя NumPy.

In [13]:
def matrix_det(matrix):
    rows_len_check(matrix)
    rows1_columns2_check(matrix, matrix)
    det = 0
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    for i, num in enumerate(matrix[0]):
        det += (-1) ** i * num * matrix_det(
            [[el for j, el in enumerate(vector) if j != i] for k, vector in enumerate(matrix) if k > 0]
        )
    return det

In [14]:
c = [[1, 2, 3, 4],
     [9, -2, 10, 6],
     [4, 0, 17, -4],
     [3, 1, 1, 111]]

In [15]:
print(matrix_det(c))
print(f'{np.linalg.det(c):.0f}')

-24534
-24534
