## Практическое задание

In [1]:
import numpy as np

### __1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}$$

$$\begin{vmatrix}
-1-\lambda & -6\\
2 & 6 - \lambda\\
\end{vmatrix}=0$$  
$$(-1-\lambda)(6-\lambda) + 12 = 0$$  
$$-6+\lambda - 6\lambda +\lambda^2+12=0$$  
$$\lambda^2 - 5\lambda +6=0$$  
$$\begin{cases}
\lambda_1+\lambda_2=5\\
\lambda_1\cdot\lambda_2=6
\end{cases} \begin{cases}
\lambda_1=2\\
\lambda_1=3
\end{cases}$$

$$\begin{pmatrix}
-1 & -6\\
2 & 6 \\
\end{pmatrix}
\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix} = 
2\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix}$$

$$\begin{cases}
-x_1-6x_2=2x_1\\
2x_1+6x_2=2x_2
\end{cases} 
\begin{cases}
x_1=-2x_2\\
2x_2=2x_2\\
\end{cases}
\begin{cases}
x_1=-2x_2\\
x_2-любое\\
\end{cases}$$

$$\begin{pmatrix}
-1 & -6\\
2 & 6 \\
\end{pmatrix}
\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix} = 
3\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix}$$

$$\begin{cases}
-x_1-6x_2=3x_1\\
2x_1+6x_2=3x_2
\end{cases} 
\begin{cases}
2x_1=-3x_2\\
3x_2=3x_2\\
\end{cases}
\begin{cases}
x_1=\frac{-3}{2}x_2\\
x_2-любое\\
\end{cases}$$

Пример собственных векторов $-\,(-2, 1);\enspace(-3, 2)$

In [3]:
a_1 = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a_1)
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

### __2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$\begin{vmatrix}
-1-\lambda & 0\\
0 & -1-\lambda\\
\end{vmatrix}=0$$  
$$(-1-\lambda)^2=0$$  
$$\lambda_1=\lambda_2=-1$$

$$\begin{pmatrix}
-1 & 0\\
0 & -1 \\
\end{pmatrix}
\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix} = 
-1\begin{pmatrix}
x_1\\
x_2\\
\end{pmatrix}$$

$$\begin{cases}
-x_1+0x_2=-1x_1\\
0x_1-1x_2=-1x_2
\end{cases}
\begin{cases}
x_1-любое\\
x_2-любое\\
\end{cases}$$

In [6]:
a_2 = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a_2)
w, v

(array([-1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

### __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



$$\begin{pmatrix}
1 & 1\\
-1 & 3 \\
\end{pmatrix}
\begin{pmatrix}
1\\
1\\
\end{pmatrix} = 
\lambda\begin{pmatrix}
1\\
1\\
\end{pmatrix}$$

$$\begin{cases}
1+1=\lambda\\
-1+3=\lambda
\end{cases}
\begin{cases}
\lambda=2\\
\lambda=2\\
\end{cases}$$

__Ответ:__ вектор $x=(1,1)$ является собственным для данного линейного оператора

### **4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4\\
\end{pmatrix} = 
\lambda\begin{pmatrix}
3\\
-3\\
-4\\
\end{pmatrix}$$

$$\begin{cases}
0\cdot3-3\cdot3+0\cdot(-4)=3\lambda\\
3\cdot3+0\cdot(-3)+0\cdot(-4)=-3\lambda\\
0\cdot3+0\cdot(-3)+3\cdot(-4)=-4\lambda
\end{cases}
\begin{cases}
-9=3\lambda\\
9=-3\lambda\\
-12=-4\lambda
\end{cases}
\begin{cases}
\lambda=-3\\
\lambda=-3\\
\lambda=3
\end{cases}$$

__Ответ:__ вектор $x=(3,-3,-4)$ __не__ является собственным для данного линейного оператора